
services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/core/src/main/resources/db/init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypass
    healthcheck:
      test: ["CMD", "mysql", "-u", "myuser", "-pmypass", "-e", "SELECT 1"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - mynetwork

  springpart:
    container_name: springpart
    build:
      context: ./backend/core
      dockerfile: docker/backend/Dockerfile
    ports:
      - "8077:8077"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - CORS_ALLOWED_ORIGINS=http://localhost,http://angularpart
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/mydb
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=mypass
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mynetwork

  angularpart:
    container_name: angularpart
    build:
      context: ./frontend
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - springpart
    networks:
      - mynetwork

volumes:
  mysql_data:

networks:
  mynetwork:
    driver: bridge
    attachable: true