services:
  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypass
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mynetwork

  springpart:
    image: ${CI_REGISTRY_IMAGE}/backend:${TAG}
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mydb
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypass
    ports:
      - "8077:8077"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mynetwork

  angularpart:
    image: ${CI_REGISTRY_IMAGE}/frontend:${TAG}
    ports:
      - "80:80"
    depends_on:
      - springpart
    networks:
      - mynetwork

volumes:
  mysql_data:

networks:
  mynetwork:
    driver: bridge